package org.spider.bus.constantes;

public enum DiasSemana {
	TODOS, SEGUNDA_SABADO, SEGUNDA_SABADO_DOMINGO, SEGUNDA_SEXTA_SABADO, SEGUNDA_SEXTA_DOMINGO, SABADO_DOMINGO, SEGUNDA_SEXTA, SABADOS, DOMINGOS, SEGUNDA_DOMINGO, NENHUM;
}
